### ISSUE TITLE
Hub methods with more than 5 arguments.

### ISSUE THREAD

**Issue by Nismonick** [AS-Devs/signalr_flutter#10]
I have tried editing the kotlin file "SignalR.kt" because i had methods with more than 5 arguments.

![image](https://user-images.githubusercontent.com/26749394/96790807-6346c700-13c5-11eb-9e9f-c4dcd9148b00.png)

but i'm still getting the error

![image](https://user-images.githubusercontent.com/26749394/96790864-76f22d80-13c5-11eb-84b0-53fb86c614b8.png)

Do I need to rebuild that package? I really can't find the next logical step to continue with this. Am I missing something?

**Comment by AyonAB** [comment]
Check the dart code of that same method. There is a validation step for number of arguments. Edit that and you should be good to go.

**Comment by itsthetaste** [comment]
you could change the Kotlin code to

val res: SignalRFuture<Any> = hub.invoke(Any::class.java, methodName, *args.toTypedArray())

so that it spreads the list into vararg for you

**Comment by AyonAB** [comment]
Well, I didn't know that! Thanks. Will take a look.  Cheers🥂
