### ISSUE TITLE
[iOS] WebView  - Origin in requests headers is always null

### ISSUE THREAD

**Issue by LukaszSadoch** [AS-Devs/signalr_flutter#14]
In webview I'a getting error:
`Origin null is not allowed by Access-Control-Allow-Origin`

My flutter app connects to server with CORS mechanism, so null is not acceptable. Adding an 'Origin' header to SignalR configuration doesn't help either.

I don't know how to change Origin to any value, but after adding allowUniversalAccessFromFileURLs to WKWebView it will be "file: //" which in my opinion is a better solution

**Comment by LukaszSadoch** [comment]
Suggestion of changes:

to file ios/Classes/SwiftR.swift:231 add:
`config.setValue(true, forKey: "allowUniversalAccessFromFileURLs")`

**Comment by AyonAB** [comment]
Thanks for the suggestion, added this. Should be available in the next pre release.
