### ISSUE TITLE
[iOS] Subscription to Hub methods is triggered only on Hub connection

### ISSUE THREAD

**Issue by LukaszSadoch** [AS-Devs/signalr_flutter#15]
It is not possible to subscribe to methods after establishing a connection via Hub - and thus events are not returned from Webview to the app.

Calling subscribeToHubMethod does not generate any error, but no  message is returned to the flutter application

**Comment by LukaszSadoch** [comment]
Suggestion of changes:

to file ios/Classes/SwiftR.swift:270 add:
` connection.runJavaScript("addHandler('\(callbackID)', '\(name)', '\(method)')")`

**Comment by AyonAB** [comment]
Okey, I haven't got time to test fully on ios after the recent changes. I applied your solution but its still not returning events for me. I think it needs more investigation.

**Comment by AyonAB** [comment]
Fixed this issue in latest pre release 0.1.0.
