### ISSUE TITLE
How do I trigger the flutter function from the server

### ISSUE THREAD

**Issue by yenge35** [AS-Devs/signalr_flutter#18]
asp.net ile yazılmış bir hub servisim var. signalR ile bağlantı kurabiliyorum. fakat sunucudan flutter daki bir fonksiyonu geri arayamıyorum. bana yardımcı olurmusunuz

**Comment by AyonAB** [comment]
You can use `HubCallback` function to communicate with client or transfer data etc.

**Comment by yenge35** [comment]
resimde işaretlediğim yer hangi isimde olması gerekiyor
[image: Ekran Alıntısı.PNG][image: Ekran Alıntısı.PNG]

Ayon Das <notifications@github.com>, 6 Oca 2021 Çar, 16:00 tarihinde şunu
yazdı:

**Comment by yenge35** [comment]
mümkünse teamwiever ile bağlanıp yardımcı olabilir misiniz? benim için çok
önemlidir.

Yasin Genç <yasingencc@gmail.com>, 6 Oca 2021 Çar, 16:05 tarihinde şunu
yazdı:

**Comment by AyonAB** [comment]
1st of all, I cant understand your language, its extremely difficult for me to communicate in this way. I cant even see the image you attached. And to answer your 2nd question, no I can't help you personally.

**Comment by yenge35** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/7754186/103772035-e200e700-5039-11eb-9865-15d15da0a9a5.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/7754186/103772071-f3e28a00-5039-11eb-937d-bcb516bc6373.PNG)

**Comment by yenge35** [comment]
kırmızı olarak işaretlediğim yer hangi isimde olması gerekiyor

**Comment by AyonAB** [comment]
You should receive that message on `_onNewMessage ` callback.

**Comment by yenge35** [comment]
tamamdır. hata şurdan kaynaklanıyormuş. iki adet parametre gönderiyormuşum. oysaki bir adet parametre alıyormuş

**Comment by yenge35** [comment]
![Uploading Ekran Alıntısı.PNG…]()

**Comment by yenge35** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/7754186/103772957-643ddb00-503b-11eb-876b-274e1c06bad4.PNG)

**Comment by yenge35** [comment]
cevap verdiğiniz için teşekkür ederim.
