### ISSUE TITLE
flutter build release mod SignalR no connection

### ISSUE THREAD

**Issue by yenge35** [AS-Devs/signalr_flutter#19]
uygulamayı derleyip apk oluşturduğumda cihazımda signal bağlantısı Unknown olarak alıyorum. oysa debug modda normal bir şekilde çalışıyor.

**Comment by yenge35** [comment]
![Screenshot_1610637197](https://user-images.githubusercontent.com/7754186/104609730-684da680-5694-11eb-81ca-c0bd935d7286.png)
debug mod ... invoke click
![Screenshot_20210114-181336](https://user-images.githubusercontent.com/7754186/104609763-700d4b00-5694-11eb-8f63-fba217c1f835.jpg)
release apk  ... invoke click

**Comment by ghulamostafa** [comment]
Maybe your client arguments are not matching or their types are not matching with your server method.
https://ghulamustafa.com/2021/01/16/how-to-use-signalr-with-flutter-for-chat/

**Comment by yenge35** [comment]
sorun şu şekilde çözüldü

flutter build apk = çalışmadı
flutter build apk --release = Çalıştı

**Comment by AyonAB** [comment]
Sorry for the late reply. You need to add a ProGuard rule for your app and this issue should go away for release builds with minify enabled. R8 is striping away some SignalR classes from the plugin which is creating this issue in release mode.

Add the following line in your `proguard-rules.pro` file,

`-keep class microsoft.aspnet.signalr.client.hubs.** { *; }`

I'll be adding this to the example app and also in the readme in near future.
