### ISSUE TITLE
Get notifications when application is closed - Check if a connection exists

### ISSUE THREAD

**Issue by AliEasy** [AS-Devs/signalr_flutter#25]
Hi
first:
I want signalr to get notifications even if my application is closed

second:
I want to check if signalr is connected before use `signalR.connect()`.
because if use `signalR.connect()` multiple times hubCallback gets called multiple times when triggered.
I used `signalR.connect()` 7 times and below is the result:
![image](https://user-images.githubusercontent.com/45623453/113286532-950f7280-9301-11eb-9d26-8e44fbee6a09.png)
callbacks happened in one trigger

Thanks in advance

**Comment by AyonAB** [comment]
Ok for the 1st issue, I don't think its possible. App notifications are there for that. 
As for the 2nd one, it will be done in the next update probably.
