### ISSUE TITLE
Error while building apk

### ISSUE THREAD

**Issue by Kedar-27** [AS-Devs/signalr_flutter#26]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:packageReleaseBundle'.                  
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > File 'root/lib/getLibs.ps1' uses reserved file or directory name 'lib'.

**Comment by mahmoudatef955** [comment]
Did you solve the problem?

**Comment by Kedar-27** [comment]
> Did you solve the problem?

Yes, had to rename signalr-client-sdk.jar file 'lib' folder to 'libs'

**Comment by baltazar888** [comment]
I get the same error while trying to build app bundle. Could you please explain in more details how did you resolve this?

Thank you.

**Comment by tech-instacare** [comment]
> > Did you solve the problem?
> 
> Yes, had to rename signalr-client-sdk.jar file 'lib' folder to 'libs'

Can you please explain further steps?

**Comment by baltazar888** [comment]
> > > Did you solve the problem?
> > 
> > 
> > Yes, had to rename signalr-client-sdk.jar file 'lib' folder to 'libs'
> 
> Can you please explain further steps?

Hello @tech-instacare 

For me worked like this:

go to your local flutter location -> flutter\.pub-cache\hosted\pub.dartlang.org\signalr_flutter-0.0.5\android\libs
right click on signalr-client-sdk.jar open with WinRAR and then just rename the folder lib to libs

I hope this will help you

**Comment by wolcy97** [comment]
1. Add build.gradle blow lines
apply plugin: 'kotlin-android-extensions'
android {  
  packagingOptions {
        exclude 'AndroidManifest.xml'
        exclude 'lib/getLibs.ps1'
        exclude 'lib/getLibs.sh'
        exclude 'lib/gson-2.2.2.jar'
    }
 }

2. Change SignalR.kt with new code 
SignalR.kt Path : flutter/.pub-cache/hosted/pub.dartlang.org/signalr_flutter-0.1.0/android/src/main/kotlin/dev/asdevs/signalr_flutter/SignalR.kt

new Code path : https://raw.githubusercontent.com/AS-Devs/signalr_flutter/master/android/src/main/kotlin/dev/asdevs/signalr_flutter/SignalR.kt

3. Clean Project 
4. Rebuild
