### ISSUE TITLE
There was a problem in the negotiation with the server.

### ISSUE THREAD

**Issue by sokheangkhun** [AS-Devs/signalr_flutter#33]
I have an ASP Core API with SignalR. For my web client using javaScript everything work fine but when I use in flutter status always respond disconnect with error message "There was a problem in the negotiation with the server".

**Comment by rajvitailor1998** [comment]
i have ASP API  with signalR still getting error message  "There was a problem in the negotiation with the server"

**Comment by BlackBearFTW** [comment]
I also have this, what can I do about it?

**Comment by AyonAB** [comment]
This plugin is for ASP.Net SignalR. ASP.Net Core SignalR won't work with this plugin.
