### ISSUE TITLE
Get Connection Id

### ISSUE THREAD

**Issue by majidfathi69** [AS-Devs/signalr_flutter#36]
I wrote this code and now I need to find out how to get the connection id from mySignalR object.
```
mySignalR = SignalR('URL', "Hub",
        hubMethods: ["GetSellsInit", "GetSells"],
        statusChangeCallback: _onStatusChange,
        queryString: "logintoken=xyz",
        hubCallback: _onNewMessage)
```

some example in javascript:
```
var connection = $.hubConnection("URL");
var hub = connection.createHubProxy("Hub");
connection.id
```

**Comment by AyonAB** [comment]
After the successful signalr connection, you can get the connection id with `mySignalR.connectionId`. Try out the pre release package if you are having any trouble. I will soon push a stable update.
