### ISSUE TITLE
How do I use it with Firebase

### ISSUE THREAD

**Issue by ahmeteminkara** [AS-Devs/signalr_flutter#37]
* Flutter 2.3.0-17.0.pre.538
* Dart 2.14.0

I am using `signalr_flutter (v0.1.2)` plugin in my flutter application. When the application is opened, I can receive notifications and messages and have no problems. But when I add the `firebase_messaging` plugin and set my project to receive background notification, signalR is not connecting. **isConnected** response incorrect, **hubCallback** and **statusChangeCallback** not responding
It works on iOS, but this problem **_only happens on Android_**.
Can you please help?

**Comment by beebobox** [comment]
hi ahmeteminkara.
Did you solve your problem?
I am experiencing the excact issue.

**Comment by ahmeteminkara** [comment]
My problem probably persists. I'm using .NET Core SignalR, not .NET SignalR anymore, on the server. I'm using the plugin "signalr_core" v1.1.1 and no longer have the problem.
