### ISSUE TITLE
Not working in release apk

### ISSUE THREAD

**Issue by ankushmourya143** [AS-Devs/signalr_flutter#39]
Hi!

I have integrate this plugin it is working fine in debug android build but in release mode it's callback not working... If want to join chat the invoked method does not return any value if i come back from chat screen its show exception like Platform Exception.

Plz suggest something.

Thanks.

**Comment by AyonAB** [comment]
I assume you are trying on android. If it is then you have to add signalr class to proguard.

**Comment by ankushmourya143** [comment]
@AyonAB thanks for your reply... It's worked in android. Can you suggest for iOS build ? I am facing same issue.

**Comment by AyonAB** [comment]
Try out the new pre-release from pub.
