### ISSUE TITLE
Cannot receive messages from server to my flutter apps

### ISSUE THREAD

**Issue by rsyd29** [AS-Devs/signalr_flutter#42]
I need help to solve my problem with my program code. When I create a new message and receive a message from the server an error occurs. When sending a message successfully entered the server, but when receiving a message from a different client the Flutter application could not receive it with an error message:

> I/flutter (12014): statusChangeCallback: ConnectionStatus.connectionError
I/flutter (12014): value: 
I/flutter (12014): response: null
I/TextInputPlugin(12014): Composing region changed by the framework. Restarting the input method.

======== Exception caught by services library ======================================================
The following PlatformException was thrown during a platform message callback:
PlatformException(channel-error, The handler has 1 parameters, but there are 2 values., null, null)

When the exception was thrown, this was the stack: 
#0      SignalR.onStatusChange (package:signalr_flutter/signalr_flutter.dart:46:7)
#1      SignalRPlatformApi.setup.<anonymous closure> (package:signalr_flutter/signalr_api.dart:277:21)
#2      SignalRPlatformApi.setup.<anonymous closure> (package:signalr_flutter/signalr_api.dart:270:35)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389:35)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:46)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#11     _invoke2 (dart:ui/hooks.dart:188:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:83:31)
(elided 3 frames from dart:async)

Flutter Code Initial Connection
![image](https://user-images.githubusercontent.com/39576704/146729538-1a32d88f-d2f0-47dc-bdf2-d808d1b36e4d.png)
![image](https://user-images.githubusercontent.com/39576704/146729755-c3db0ad4-ca45-44d6-ad65-58861aea956e.png)

Flutter Code Method sendMessage
![image](https://user-images.githubusercontent.com/39576704/146729696-76baa596-7d2a-48da-9b10-7fefc29254ce.png)

.Net Server Code
![image](https://user-images.githubusercontent.com/39576704/146730056-f757bcbe-0311-4858-89b2-58ed1ff30305.png)

**Comment by rsyd29** [comment]
The issue has been resolved. The method Send method in the ChatHub class has one argument/parameter with a String data type. To be able to retrieve more than one data, use Map<String, dynamic> to String.

This is my code to learn what i mean
[Code Flutter](https://github.com/rsyd29/latihan_signalr_framework_chat)
[Code .Net Framework](https://github.com/rsyd29/SignalRFrameworkChat)

**Comment by gongwangjie** [comment]
Everything works fine in the debug environment. If you use the release version, you can connect to the server but cannot receive messages sent by the server. Have you encountered this situation?
