### ISSUE TITLE
"channel-error" means what?

### ISSUE THREAD

**Issue by chenshaxuanjing** [AS-Devs/signalr_flutter#43]
error:
![微信截图_20220511193935](https://user-images.githubusercontent.com/32640500/167841573-923cb8cd-4502-4054-a386-35aab321486f.png)

my code:
![微信截图_20220511194007](https://user-images.githubusercontent.com/32640500/167841980-2e73bc36-44b1-48a6-8974-b75c5727c09b.png)

` Future<void> createSocket() async{
    String token = await getAccessToken();
    signalR = SignalR(
      serverUrl,
      "hubs/arkhub",
      hubMethods: ["onOrderMatched","onOrderCancelled","onOrderCancelled"],
      headers: {"Authorization":"Bearer "+token},
      statusChangeCallback: _onStatusChange,
      hubCallback: _onNewMessage,
    );

  }

  Future<void> startSocket() async{
    final isConnected = await signalR.isConnected();
    if (!isConnected) {
      final connId = await signalR.connect();
      print("Connection ID: $connId");
    } else {
      signalR.stop();
    }

  }`

**Comment by joseph-lewis** [comment]
Having the same error...

**Comment by bhavykoshti** [comment]
+1 same error and its a platform exception so its showing in crashlytics too.
Need to remove this lines from the library

```
if (statusChangeResult.errorMessage != null) {
  throw PlatformException(code: 'channel-error', message: statusChangeResult.errorMessage);
}
```
