### ISSUE TITLE
Android gradle namespace missing for newer android versions

### ISSUE THREAD

**Issue by devaronius** [AS-Devs/signalr_flutter#67]

**Comment by AngeloPavan** [comment]
Hello @devaronius , may I ask you if you've fixed this somehow?

**Comment by mohammedsaidm** [comment]
How to solve this please ????? @devaronius @AngeloPavan @mohas @AyonAB

**Comment by AngeloPavan** [comment]
@mohammedsaidm Hello, I've made a fork, I have used it some months ago and it was fine, you might as well try it

https://github.com/AngeloPavan/signalr_flutter_fix

**Comment by mohammedsaidm** [comment]
@AngeloPavan Great thanks it is working fine now.
