### ISSUE TITLE
Numbers (_int_ / _ushort_) are returned as _double_

### ISSUE THREAD

**Issue by Chyur** [AS-Devs/signalr_flutter#8]
Hi.
Substitution of return number types was detected.

Server code:
```
public class NotificationHub : Hub
{
...
  public int GetCurrentState()
  {
    return MvcApplication.CurrentState;
  }

  public Dictionary<string, ushort[]> GetDictionaryMParams()
  {
    Dictionary<string, ushort[]> dictionary = null;

    var controller = DependencyResolver.Current.GetService<MParamsController>();
    MParams mParams = controller.GetFirstMParams();
    if(mParams != null) {
      dictionary = new Dictionary<string, ushort[]>();
      AddMDictionary(dictionary, "par1", mParams.par1);
      AddMDictionary(dictionary, "par2", mParams.par2);
    }
    return dictionary;
  }
}
```
First example.
On the server: MvcApplication.CurrentState is 1 (_int_).
Log for int GetCurrentState(), version 0.0.5:
`[log] int GetCurrentState(): value = 1.0 / value.runtimeType: double`
(For comparison, version 0.0.4:
`[log] int GetCurrentState(): value = 1 / value.runtimeType: String`)

Second example.
On the server: dictionary["par1"][0] is 132 (_ushort_), but it's returned inside the object as _double_.
Log for Dictionary<string, ushort[]> GetDictionaryMParams() in the last (0.0.5) version:
`[log] Dictionary<string, ushort[]> GetDictionaryMParams(): value["par1"][0] = 132.0 / value["par1"][0].runtimeType: double`

Is it possible to fix this substitution?
Thanks

**Comment by AyonAB** [comment]
Just convert the value to integer. You have many options to do that in dart.
```dart
double d = 20.5;

int i = d.toInt(); // i = 20
int i = d.round(); // i = 21
int i = d.ceil();  // i = 21
int i = d.floor(); // i = 20
```

**Comment by Chyur** [comment]
Sorry, but the question is not about the obvious conversion in dart.
I will repeat it: is it possible to get numbers (as the output of the plugin) of the same types as on the server?

**Comment by AyonAB** [comment]
If you take a look at the return type of that `invokeMethod`, you can see its dynamic. So it should be the same as the return from your server. Now if you are getting int as double then that must be a internal Dart thing. Currently it is not possible to specify the type of a return from a particular server method. I may take a look at that in the future though.
