### ISSUE TITLE
java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path 

### ISSUE THREAD

**Issue by tayyyab** [AS-Devs/signalr_flutter#9]
I get this message on HubCallBack methods. The issue only exists in the Android.

`I/flutter ( 8673): java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $`

_signalRCallbackHandler Throws an exception.

**Comment by AyonAB** [comment]
What version of the plugin are you using?
If you are not using latest version then, then change it to the latest, which is v0.0.5 and do a `flutter clean` after that.

**Comment by tomgoth07** [comment]
i have the same issus:
java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $
 happen when the backend send an object.

**Comment by AyonAB** [comment]
Although I'm little confused as why `StatusChangeCallback` is raising this exception cause it was meant to be `String`. I couldn't quite reproduce the issue but anyway did some changes for a possible fix. @tayyyab or @tomasgaray if any one of you can grab the latest pre-release version (0.0.6-dev.1) from the pub and test it, I'll be glad for that help.

**Comment by itsthetaste** [comment]
yes I can confirm that this is working for me now

**Comment by AyonAB** [comment]
Thank you for the feedback and as for the `hubCallBack`, I'll looking into it once I get some time.

**Comment by furkansoylemez** [comment]
im getting this exception when server sends a json. Its ok with receiving strings but im in trouble with jsons. Any suggestions? @AyonAB
